version: 2.1

orbs:
  node: circleci/node@5.0.2

commands:
  login:
    description: "Log in to Artifactory, allowing to install private @activeviam dependencies."
    steps:
      - run:
          name: Log into artifactory & Link @activeviam packages to the internal registry
          command: |
            npx npm-cli-adduser --registry https://activeviam.jfrog.io/artifactory/api/npm/npm-internal/ --scope @activeviam --username $CROWD_USERNAME --password $CROWD_PASSWORD --email activeui@activeviam.com
            npm config set @activeviam:registry https://activeviam.jfrog.io/artifactory/api/npm/npm-internal/

jobs:
  build-and-test:
    executor:
      name: node/default
      tag: "18.12.1"
    resource_class: xlarge
    steps:
      - checkout
      - login
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn lint
      - run: yarn ci:test

workflows:
  # Used to protect the main branch: it should block merging into main when failing.
  # See https://github.com/activeviam/activeui-migration/settings/branch_protection_rules/15886613
  check-pull-request:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - main
