version: 2.1

orbs:
  node: circleci/node@5.0.2

commands:
  login:
    description: "Log in to Artifactory, allowing to install private @activeviam dependencies."
    steps:
      # Authenticate on the our private NPM registry, to be able to fetch dependencies such as @activeviam/activeui-sdk from it.
      # See https://www.jfrog.com/confluence/display/JFROG/npm+Registry#npmRegistry-ConfiguringthenpmClientforaScopeRegistry
      # The credentials are interpolated "manually" since CircleCI does not support environment variables interpolation in the configuration (see https://circleci.com/docs/env-vars/#parameters-and-bash-environment).
      - run:
          name: Authenticate on Artifactory
          command: >-
            echo $CROWD_USERNAME:$CROWD_PASSWORD | xargs -I {}
            curl -u '{}' https://activeviam.jfrog.io/artifactory/api/npm/npm-internal/auth/activeviam
            > ~/.npmrc

jobs:
  build-and-test:
    executor:
      name: node/default
      tag: "18.12.1"
    resource_class: xlarge
    steps:
      - checkout
      - login
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn lint
      - run: yarn ci:test

workflows:
  # Used to protect the main branch: it should block merging into main when failing.
  # See https://github.com/activeviam/atoti-ui-migration/settings/branch_protection_rules/15886613
  check-pull-request:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - main
